let mock = [{
    id: 1,
    name: "Morbius",
    genre: "Action, Adventure, Sci-Fi",
    release: "July 31, 2020",
    rating: "N/A",
    length: "N/A",
    image: 'Morbius.jpg',
    watchlist: "Add to Watchlist",
},
  {
    id: 2,
    name: "Black Widow",
    genre: "Action, Adventure, Sci-Fi",
    release: "May 1, 2020",
    rating: "N/A",
    length: "N/A",
    image: 'BlackWidow.jpg',
    watchlist: "Add to Watchlist",
},
  {
    id: 3,
    name: "The Eternals",
    genre: "Action, Adventure, Fantasy",
    release: "Nov 6, 2020",
    rating: "N/A",
    length: "N/A",
    image: 'TheEternals.jpg',
    watchlist: "Add to Watchlist",
},
  {
    id: 4,
    name: "Shang-Chi and the Legend of the Ten Rings",
    genre: "Action, Adventure, Fantasy",
    release: "Feb 12, 2021",
    rating: "N/A",
    length: "N/A",
    image: 'ShangChi.jpg',
    watchlist: "Add to Watchlist",
},
  {
    id: 5,
    name: "Doctor Strange in the Multiverse of Madness",
    genre: "Action, Adventure, Fantasy",
    release: "May 7, 2021",
    rating: "N/A",
    length: "N/A",
    image: 'DoctorStrangeintheMultiverseofMadness.jpg',
    watchlist: "Add to Watchlist",
},
  {
    id: 6,
    name: "Thor: Love and Thunder",
    genre: "Action, Adventure, Fantasy",
    release: "Nov 5, 2021",
    rating: "N/A",
    length: "N/A",
    image: 'ThorLoveandThunder.jpg',
    watchlist: "Add to Watchlist",
}
]

export default mock;
